### ISSUE TITLE
Research MongoDB in connection with Android

### ISSUE THREAD

**Issue by mflippen** [UF-ACE/Spring2022PhoneAppProject#13]

**Comment by ChristopherJMiller** [comment]
It seems I got auto subscribed to this repo via the github org and I have a little advice to chime in with 🙂

The way communication is usually done between a mobile client app and the database is through some sort of backend. Usually, this is a web server, and depending on what sort of actions are required (reading data versus writing data) you can create authentication processes between the app and that backend (e.g. a user has to log in in order to make changes to data that is stores in the database). I would recommend against any avenues where you would be storing sensitive credentials on the phone itself, since this has privacy concerns and isn't good practice. But, I understand in the usual scope of these projects it might be a lot to tack on an entire web server to the project, it's just something to keep in mind if you want to take the skills you learn here into a work setting.
